In [25]:
import numpy as np
import pandas as pd

In [26]:
data = pd.read_csv("C:/Users/balto/OneDrive/Desktop/CMPE257/CMPE257_HW3/Real estate.csv")

In [27]:
data.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [29]:
demo_test = data[['X1 transaction date', 'X2 house age']]
demo_test.head()

X1 transaction date  X2 house age
0             2012.917          32.0
1             2012.917          19.5
2             2013.583          13.3
3             2013.500          13.3
4             2012.833           5.0

In [30]:
scaler.fit_transform(demo_test)

array([[0.27292576, 0.73059361],
       [0.27292576, 0.44520548],
       [1.        , 0.30365297],
       [0.90938865, 0.30365297],
       [0.18122271, 0.11415525],
       [0.        , 0.16210046],
       [0.        , 0.78767123],
       [0.81877729, 0.46347032],
       [0.90938865, 0.72374429],
       [0.81877729, 0.4086758 ],
       [0.45414847, 0.79452055],
       [0.72707424, 0.14383562],
       [0.27292576, 0.29680365],
       [0.        , 0.46575342],
       [0.90938865, 0.30136986],
       [1.        , 0.81506849],
       [0.63646288, 0.        ],
       [0.09061135, 0.40410959],
       [0.81877729, 0.38584475],
       [0.        , 0.03424658],
       [0.81877729, 0.10273973],
       [0.81877729, 0.23972603],
       [0.27292576, 0.33561644],
       [0.45414847, 0.23059361],
       [0.36353712, 0.90410959],
       [0.45414847, 0.66894977],
       [0.        , 0.07077626],
       [0.63646288, 0.23744292],
       [0.90938865, 0.43835616],
       [0.45414847, 0.16210046],
       [0.

In [31]:
scaler.data_max_

array([2013.583,   43.8  ])

In [32]:
scaler.data_min_

array([2012.667,    0.   ])